source 'https://rubygems.org'

# Use sqlite3 as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', git: 'https://github.com/rails/sass-rails'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Use debugger, unless using RubyMine which conflicts with the debugger gem
gem 'debugger', {group: [:test, :development]}.merge(ENV['RM_INFO'] ? {require: false} : {})

# Better Errors replaces the standard Rails error page with a much better and more useful error page.
gem 'better_errors'
# Required by better_errors
gem 'binding_of_caller'

# Mutes assets pipeline log messages.
gem 'quiet_assets'

# Required for Rails Panel (https://chrome.google.com/webstore/detail/railspanel/gjpfobpafnhjhbajcjgccbbdofdckggg)
gem 'meta_request'

# Pry is a powerful alternative to the standard IRB shell for Ruby.
gem 'pry'

# Spree ecommerce store
gem 'spree', git: 'https://github.com/spree/spree'
gem 'spree_auth_devise', git: 'https://github.com/spree/spree_auth_devise'
gem 'spree_zoned', path: '../'
